name = "Cumulative"
author = "Chris Tomlin"
version = "1.35.1+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d992365c65a223d93e1fdb4ea504edaab13fbaf9005c75aef63bf8f0a3d2c03a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
